---

# drop in DE rulesets

- name: python2-pika is a requirement
  yum: name=python2-pika state=latest

- name: copy DE rulesets into place
  sudo: yes
  sudo_user: irods
  copy: src={{item}} dest=/etc/irods/ owner=irods group=irods mode=0644
  with_items:
    - core.re
    - ipc-amqp.re
    - ipc-custom.re
    - ipc-json.re
    - ipc-logic.re
    - ipc-uuid.re

- name: place ipc-env.re template into place
  sudo: yes
  sudo_user: irods
  template: src=ipc-env.re.j2 dest=/etc/irods/ipc-env.re owner=irods group=irods mode=0644

- name: copy DE scripts into iRODS bin/ directory
  sudo: yes
  sudo_user: irods
  copy: src={{item}} dest=/var/lib/irods/msiExecCmd_bin owner=irods group=irods mode=0755
  with_items:
    - amqpsend.py
    - amqptopicsend.py
    - generateuuid.sh

- name: place libmsiSetAVU.so plugin 
  sudo: yes
  sudo_user: irods
  copy: src=libmsiSetAVU.so dest=/var/lib/irods/plugins/microservices/ owner=irods group=irods mode=0644

- name: echo ruleset warning
  debug: msg="Custom DE iRODS rulebases installed, including core.re. Please activate rules as needed by adding them to /etc/irods/server_config.json beneath re_rulebase_set and restarting iRODS."
