---

# Development headers and libraries
# ---------------------------------

- name: Install development headers
  when: postgresql_dev_headers == True and
        ansible_os_family == "Debian"
  sudo: yes
  apt:
    name: libpq-dev
  tags:
    - postgresql
    - db
    - deps
    - dev


# Contributed extensions
# ----------------------

- name: Install PostgreSQL contribs
  when: postgresql_contrib and
        ansible_os_family == "Debian"
  sudo: yes
  apt:
    name: "postgresql-contrib-{{postgresql_version}}"
  notify: restart postgresql
  tags:
    - postgresql
    - db
    - deps

# PostGIS
# -------

- name: Add postgis extensions
  when: postgresql_postgis and
        ansible_os_family == "Debian"
  sudo: yes
  apt:
    name: "{{item}}"
  with_items:
    - "postgresql-{{postgresql_version}}-postgis-{{postgresql_postgis_version}}"
    - libgeos-c1
  notify: restart postgresql
  tags:
    - postgresql
    - db
    - deps

- name: install devel, contrib and postgis on CentOS7
  yum: name={{item}} state=latest
  with_items:
    - libpqxx-devel
    - postgresql94-contrib
    - postgis
  when: ansible_distribution == "CentOS" and
        ansible_distribution_major_version == "7"
