
- name: Add postgres repository for Debian
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present
  when: ansible_os_family == "Debian" and
        ansible_distribution_major_version == "14"

- name: Add postgres repository key for Debian
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present
  when: ansible_os_family == "Debian" and
        ansible_distribution_major_version == "14"

- name: ensure apt cache is up to date for Debian
  apt: update_cache=yes
  when: ansible_os_family == "Debian"

- name: ensure packages are installed for Debian
  apt: name={{item}} state=present
  with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2
  when: ansible_os_family == "Debian"

- name: install CentOS 7 Postgres repository
  yum: name=http://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-2.noarch.rpm state=present
  when: ansible_distribution == "CentOS" and
        ansible_distribution_major_version == "7"
  environment:
       http_proxy: "{{ proxy_env.http_proxy }}"
       https_proxy: "{{ proxy_env.https_proxy }}"

- name: ensure packages are installed for CentOS7
  yum: name={{item}} state=latest
  with_items:
        - postgresql94-server
        #- libpqxx-devel #screws up dependencies
        - python-psycopg2
  when: ansible_distribution == "CentOS" and
        ansible_distribution_major_version == "7"

- name: init postgres if necessary
  shell: "/usr/pgsql-9.4/bin/postgresql94-setup initdb"
  when: ansible_distribution == "CentOS" and
        ansible_distribution_major_version == "7"
  ignore_errors: true

- name: enable postgres for CentOS7
  service: name=postgresql-9.4 enabled=yes
  when: ansible_distribution == "CentOS" and
        ansible_distribution_major_version == "7"
 
