---

- name: stop firewalld, if running
  service: name=firewalld state=stopped
  ignore_errors: true

- name: mask firewalld service
  sudo: yes
  shell: systemctl mask firewalld

- name: install iptables-services
  yum: name=iptables-services state=latest

- name: insert iptables template
  template: src=iptables.j2 dest=/etc/sysconfig/iptables

- name: and its init script for old-schoolers
  copy: src=iptables dest=/etc/init.d/iptables owner=root group=root mode=0755

- name: restart iptables, enable at boot
  service: name=iptables state=restarted enabled=yes

- name: restart docker on docker-ready hosts
  service: name=docker state=restarted
  when: ('docker-ready' in group_names)
  ignore_errors: true

- name: enable iptables at boot
  service: name=iptables state=restarted enabled=yes
