---
- name: install centos7 postgresql96 yum repo file
  become: true
  yum:
    name: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm
    state: present
  when: ansible_distribution == "CentOS" and
        ansible_distribution_major_version == "7"

- name: postgresql is installed via yum
  become: true
  yum: name=postgresql96 state=present
  when: ansible_distribution == "CentOS"

- name: psycopg2 is installed via yum
  become: true
  yum: name=python-psycopg2 state=present
  when: ansible_distribution == "CentOS"
