- name: ldap ensure ldapscripts.conf exists
  file: name=/etc/ldapscripts state=directory owner=root group=root mode=0755
  tags:
    - ldap
    - auth

- name: copy ldapscripts template
  template: src=root/etc/ldapscripts/ldapscripts.conf.j2 dest=/etc/ldapscripts/ldapscripts.conf owner=root group=root
  tags: 
    - ldap
    - auth

- name: ldap Install add user template
  template: src=root/etc/ldapscripts/ldapadduser.template.j2 dest=/etc/ldapscripts/ldapadduser.template owner=root group=root
  tags: 
    - ldap
    - auth

- name: ldap ensure ldap.secret exists
  template: src=root/etc/ldap.secret.j2 dest=/etc/ldap.secret owner=root group=root mode=0400
  tags: 
    - ldap
    - auth

# This is really goofy but editing the secrets file in vims leaves an extra space at the end. Not sure what all editors do this
# # If your editor does not do this then this command will mess up your file.
# - name: ldap ensure ldap.secret has no trailing space
#   command: truncate --size {{ldap.password_size}} /etc/ldap.secret
#
