- name: ldap Copy over the Users and Groups ldif 
  template: src=create_users_and_groups_ous.ldif.j2 dest=/tmp/create_users_and_groups_ous.ldif owner=root group=root
  when: ldap.include_create_user_and_groups
  tags: 
    - ldap 
    - auth

#- name: Display all variables/facts known for a host
#  debug: var={{ldap.dc}}

- name: ldap create users and groups OUs
  shell: ldapadd -w {{ldap.password}} -x -D {{ ldap.manager_dn }} -f create_users_and_groups_ous.ldif && touch {{ldap_create_user_and_groups_ous_done}} chdir=/tmp creates={{ldap_create_user_and_groups_ous_done}}
  when: ldap.include_create_user_and_groups
  tags: 
    - ldap 
    - auth 

- name: ldap Copy over the indexes ldif
  template: src=root/tmp/create_indexes.ldif.j2 dest=/tmp/create_indexes.ldif owner=root group=root
  when: ldap.include_create_indexes
  tags: 
    - ldap
    - auth

- name: ldap Copy over the test de ldif if flagged for test setup
  template: src=create_builtin_users.ldif.j2 dest=/tmp/create_builtin_users.ldif owner=root group=root
  when: ldap.include_builtins
  tags:
    - ldap
    - auth


- name: ldap Install built-in DE users
  shell: ldapadd -w {{ldap.password}} -x -D {{ ldap.manager_dn }} -f create_builtin_users.ldif && touch {{ldap_create_builtins_done}} chdir=/tmp creates={{ldap_create_builtins_done}}
  when: ldap.include_builtins
  tags:
    - ldap
    - auth
