# Set de_config_dir to the local directory.
# Example: ansible-playbook -i inventories/production.cfg  --extra-vars "de_config_dir=$(pwd)/foo playbook=playbooks/local-services-cfg.yml owner=$(whoami) group=staff de_env=production" --tags="service_config,logging_config" single-role.yaml
---
- hosts: localhost
  sudo: false
  gather_facts: false
  vars_files:
    - ../group_vars/{{de_env}}
  pre_tasks:

    - name: twiddle owner and group to avoid shooting ones self in foot
      file: path={{local_cfg_dest}} owner={{ansible_ssh_user}} group={{ansible_ssh_user}} mode=0755 recurse=true
      sudo: true

    - name: create the output directory
      file: path={{local_cfg_dest}}/iplant/de state=directory
      tags:
        - service_config

    - name: create the logging directory
      file: path={{local_cfg_dest}}/iplant/de/logging state=directory
      tags:
        - logging_config

    - name: create the logstash-forwarder directory
      file: path={{local_cfg_dest}}/logstash-forwarder state=directory
      tags:
        - logging_config

    - name: create the nginx config
      file: path={{local_cfg_dest}}/nginx state=directory
      tags:
        - service_config

  roles:
    - role: util-cfg-service
      service_name_short: "{{anon_files.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{apps.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{clockwork.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{condor_log_monitor.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{data_info.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{dewey.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{exim.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{info_typer.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{infosquito.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{iplant_email.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{iplant_groups.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{jexevents.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{kifshare.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{metadata.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{monkey.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{notificationagent.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{saved_searches.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{terrain.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{tree_urls.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{user_preferences.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{user_sessions.service_name_short}}"

    - role: util-cfg-service
      service_name_short: "{{templeton_periodic.service_name_short}}"
      src: "templeton-periodic.yaml.j2"
      dest: "{{local_cfg_dest}}/templeton-periodic.yaml"

# new to dev branch, probably don't need yet
#    - role: util-cfg-service
#      service_name_short: "{{templeton_incremental.service_name_short}}"
#      src: "templeton-incremental.yaml.j2"
#      dest: "{{local_cfg_dest}}/templeton-incremental.yaml"

    - role: util-cfg-service
      src: "ui/de-application.yaml.j2"
      dest: "{{local_cfg_dest}}/de-application.yaml"
      service_name_short: "{{de.service_name_short}}"

    - role: util-cfg-service
      src: "ui/de.properties.j2"
      dest: "{{local_cfg_dest}}/de.properties"
      service_name_short: "{{de.service_name_short}}"

    - role: util-cfg-service
      src: "ui/nginx.conf.j2"
      dest: "{{local_cfg_dest}}/nginx/nginx.conf"
      service_name_short: "{{de.service_name_short}}"

    - role: util-cfg-service
      src: "docker-cleanup/docker-gc-exclude-containers.j2"
      dest: "{{local_cfg_dest}}/docker-gc-exclude-containers"
      service_name_short: "docker-gc"

    - role: util-cfg-service
      src: "docker-cleanup/docker-gc-exclude.j2"
      dest: "{{local_cfg_dest}}/docker-gc-exclude"
      service_name_short: "docker-gc"

    - role: util-cfg-service
      service_name_short: jobservices
      service_cfg_file_name: jobservices.yml

# permissions appears to be new - check w/ dennis for example group_vars?
#    - role: util-cfg-service
#      service_name_short: "{{permissions.service_name_short}}"
#      src: "permissions.yaml.j2"
#      dest: "{{service_conf_dir}}/permissions.yaml"
