---

- name: install epel repository
  yum: name=epel-release state=latest
  when: ansible_os_family == "RedHat"

- name: install server prereqs
  yum: name={{ item }} state=latest
  with_items:
    - curl
    - libselinux-python
    - python-simplejson
    - python-httplib2
    #- python-pip
  environment:
     http_proxy: "{{ proxy_env.http_proxy }}"
     https_proxy: "{{ proxy_env.https_proxy }}"

- name: install latest version of pip
  shell: "easy_install pip"

- name: add the iplant group
  group: name=iplant state=present

- name: add the iplant user
  user: name=iplant shell=/bin/bash groups=iplant append=yes uid=1337

- name: add the iplant user to docker group
  user: name=iplant groups=docker append=yes
  when: ('docker-ready' in group_names)
