---
# tasks file for infra-condor-exec-jar

- name: Place the systemd tmpfile
  become: true
  copy: src=executable-jar.conf dest=/usr/lib/tmpfiles.d/
  tags:
      - config
      - config_executable_jar

