
#
# Properties file configuration
#
- name: ensure data directory exists
  file: path=/etc/cas state=directory owner={{ cas.tomcat_user }} group={{ cas.tomcat_group }}
  tags:
    - cas
    - properties

- name: copy all template configs
  template: src=config/cas.properties dest=/etc/cas/cas.properties
  tags:
    - cas
    - properties

- name: copy log4j.xml
  copy: src=log4j.xml dest=/etc/cas/ owner={{ cas.tomcat_user }} group={{ cas.tomcat_group }}
  tags:
    - cas
    - properties

- name: set data ownership [all data is owned by tomcat]
  file: path=/etc/cas owner={{ cas.tomcat_user }} group={{ cas.tomcat_group }} recurse=true
  tags:
    - cas
    - properties
