# assets
cas_version: "1.3.1"
cas_artifactId: "ala-cas"
cas_classifier: ''
cas_packaging: "war"
cas_war_url: "{{maven_repo_ws_url}}"

cas_tomcat_java_opts_override: "-Xmx4g -Xms2g -XX:MaxPermSize=256m -Xss256k -XX:+UseG1GC"
